apiVersion: v1
kind: Service
metadata:
  name: flask-todo-service
  labels:
    app: flask-todo
spec:
  type: LoadBalancer
  selector:
    app: flask-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000