apiVersion: v1
kind: Service
metadata:
  name: flask-todo-service
  labels:
    app: flask-todo-app
spec:
  type: LoadBalancer
  selector:
    app: flask-todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80