name: CI/CD Pipeline with EKS Provisioning

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: jayyp2op/flask-todo-app:latest

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }} # Note: DATADOG_APP_KEY is in env but not used in -var, check if your TF needs it
          BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
        run: |
          terraform apply -auto-approve \
            -var="datadog_api_key=$DATADOG_API_KEY" \
            -var="bugsnag_api_key=$BUGSNAG_API_KEY"

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest' # You might want to pin this to a specific version

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name flask-todo-cluster --region ${{ secrets.AWS_REGION }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest' # You might want to pin this to a specific version

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Install Datadog via Helm
        run: |
          helm repo add datadog https://helm.datadoghq.com
          helm repo update
          helm upgrade --install datadog datadog/datadog \
            --set datadog.apiKey=${{ secrets.DATADOG_API_KEY }} \
            --set datadog.site='datadoghq.com' \
            --set datadog.logs.enabled=true \
            --set datadog.apm.enabled=true \
            --set datadog.processAgent.enabled=true \
            --set agents.containerLogs.enabled=true \
            --set datadog.env=production \
            --set targetSystem=linux \
            --namespace datadog \
            --create-namespace

      - name: Inject Environment Variables
        run: |
          kubectl set env deployment/flask-todo-app \
            DATADOG_API_KEY=${{ secrets.DATADOG_API_KEY }} \
            BUGSNAG_API_KEY=${{ secrets.BUGSNAG_API_KEY }}