name: Terraform Destroy

on:
  workflow_dispatch:  # enables manual trigger from GitHub UI

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_region: ap-south-1  # adjust if needed
      AWS_REGION: ap-south-1     # optional, for consistency

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # or your preferred version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve